language: php
php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
# 0) Prerequisites.
# 0.1) Create Drupal database.
 - mysql -e 'create database drupal;'
# 0.2) Install Drush.
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush-devel
# 0.3) Install & prepare Drupal.
 - phpenv rehash
 - cd ..
 - ls -la
 # --no-cache is must-have due to http://drupal.org/node/1630220
 - drush dl drupal-7 --dev --no-cache
 - cd drupal-*
 - cp -R ../apachesolr sites/all/modules/apachesolr
 - drush si standard --db-url=mysql://root:@localhost/drupal --yes
 - drush en simpletest --yes
# 1) Download and configure Apachesolr before enabling Drupal module.
# @todo Do not hardcode current version, use the latest.
 - cd ..
# 1.1) Download & extract the latest Apachesolr.
 - wget http://apache.mesi.com.ar/lucene/solr/3.6.2/apache-solr-3.6.2.tgz
 - tar -xvzf apache-solr-3.6.2.tgz
# 1.2) Replace configuration files.
 - cd apache-solr-3.6.2
# @todo Remove it.
# 1.2.1) schema.xml
# - mv example/solr/conf/schema.xml schema.bak
# - cp ../apachesolr/solr-conf/solr-3.x/schema.xml example/solr/conf/schema.xml
# 1.2.2) solrconfig.xml
# - mv example/solr/conf/solrconfig.xml solrconfig.bak
# - cp ../apachesolr/solr-conf/solr-3.x/solrconfig.xml example/solr/conf/solrconfig.xml
# 1.2.3) protwords.txt
# - mv example/solr/conf/protwords.txt protwords.bak
# - cp ../apachesolr/solr-conf/solr-3.x/protwords.txt example/solr/conf/protwords.txt
# 1.2.4) solrcore.properties
# - cp ../apachesolr/solr-conf/solr-3.x/solrcore.properties example/solr/conf/solrcore.properties
#
# 1.2.1) Backup configuration files.
 - mv example/solr/conf/schema.xml schema.bak
 - mv example/solr/conf/solrconfig.xml solrconfig.bak
 - mv example/solr/conf/protwords.txt protwords.bak
# 1.2.2) Copy necessary configuration files.
 - cp ../apachesolr/solr-conf/solr-3.x/* example/solr/conf
# 2) Start Apachesolr.
 - cd example
 - java -jar start.jar
# 3) Enable Drupal module.
 - drush en apachesolr --yes
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - sleep 4
 - drush vset simpletest_verbose TRUE --yes

script: #drush test-run --xml --uri=http://127.0.0.1:8080 SimpleNewsAdministrationTestCase,SimpleNewsI18nTestCase,SimpleNewsUpgradePath61TestCase,SimpleNewsUpgradePath62TestCase,SimplenewsSendTestCase,SimplenewsSourceTestCase,SimplenewsSubscribeTestCase,SimplenewsUnitTest
  php scripts/run-tests.sh --php ~/.phpenv/versions/5.4.13/bin/php --url 'http://127.0.0.1:8080' --verbose --file modules/apachesolr/apachesolr.test
